development:
  TokenInterface:
    deploy: false
  Token:
    gas_limit: 1000000
    gas_price: 10000000000000
    args: 
      - 100000
  SimpleStorageInterface:
    deploy: false
  DeployRelay:
    gas_limit: 1000000
    gas_price: 10000000000000
staging:
